[2025-09-06T06:32:29.407+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: mysql_insert_select.wait_for_model_file manual__2025-09-06T06:32:10.033634+00:00 [queued]>
[2025-09-06T06:32:29.424+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: mysql_insert_select.wait_for_model_file manual__2025-09-06T06:32:10.033634+00:00 [queued]>
[2025-09-06T06:32:29.425+0000] {taskinstance.py:1331} INFO - Starting attempt 1 of 1
[2025-09-06T06:32:29.448+0000] {taskinstance.py:1350} INFO - Executing <Task(FileSensor): wait_for_model_file> on 2025-09-06 06:32:10.033634+00:00
[2025-09-06T06:32:29.461+0000] {standard_task_runner.py:57} INFO - Started process 131 to run task
[2025-09-06T06:32:29.466+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'mysql_insert_select', 'wait_for_model_file', 'manual__2025-09-06T06:32:10.033634+00:00', '--job-id', '387', '--raw', '--subdir', 'DAGS_FOLDER/mysql_insert_select.py', '--cfg-path', '/tmp/tmpbi71rye7']
[2025-09-06T06:32:29.470+0000] {standard_task_runner.py:85} INFO - Job 387: Subtask wait_for_model_file
[2025-09-06T06:32:29.547+0000] {task_command.py:410} INFO - Running <TaskInstance: mysql_insert_select.wait_for_model_file manual__2025-09-06T06:32:10.033634+00:00 [running]> on host aa138fcfe7d7
[2025-09-06T06:32:29.701+0000] {taskinstance.py:1570} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='mysql_insert_select' AIRFLOW_CTX_TASK_ID='wait_for_model_file' AIRFLOW_CTX_EXECUTION_DATE='2025-09-06T06:32:10.033634+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-09-06T06:32:10.033634+00:00'
[2025-09-06T06:32:29.713+0000] {base.py:73} INFO - Using connection ID 'fs_default' for task execution.
[2025-09-06T06:32:29.714+0000] {filesystem.py:64} INFO - Poking for file /opt/***/models/LogisticRegressionModel.pkl
[2025-09-06T06:32:59.765+0000] {base.py:73} INFO - Using connection ID 'fs_default' for task execution.
[2025-09-06T06:32:59.767+0000] {filesystem.py:64} INFO - Poking for file /opt/***/models/LogisticRegressionModel.pkl
[2025-09-06T06:33:29.811+0000] {base.py:73} INFO - Using connection ID 'fs_default' for task execution.
[2025-09-06T06:33:29.812+0000] {filesystem.py:64} INFO - Poking for file /opt/***/models/LogisticRegressionModel.pkl
[2025-09-06T06:33:59.854+0000] {base.py:73} INFO - Using connection ID 'fs_default' for task execution.
[2025-09-06T06:33:59.855+0000] {filesystem.py:64} INFO - Poking for file /opt/***/models/LogisticRegressionModel.pkl
[2025-09-06T06:34:29.897+0000] {base.py:73} INFO - Using connection ID 'fs_default' for task execution.
[2025-09-06T06:34:29.897+0000] {filesystem.py:64} INFO - Poking for file /opt/***/models/LogisticRegressionModel.pkl
[2025-09-06T06:34:35.993+0000] {local_task_job_runner.py:299} WARNING - State of this instance has been externally set to restarting. Terminating instance.
[2025-09-06T06:34:35.995+0000] {process_utils.py:135} INFO - Sending Signals.SIGTERM to group 131. PIDs of all processes in the group: [131]
[2025-09-06T06:34:35.996+0000] {process_utils.py:86} INFO - Sending the signal Signals.SIGTERM to group 131
[2025-09-06T06:34:35.996+0000] {taskinstance.py:1540} ERROR - Received SIGTERM. Terminating subprocesses.
[2025-09-06T06:34:36.009+0000] {taskinstance.py:1847} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/sensors/base.py", line 253, in execute
    time.sleep(self._get_next_poke_interval(started_at, run_duration, try_number))
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1542, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal
[2025-09-06T06:34:36.015+0000] {taskinstance.py:1373} INFO - Marking task as UP_FOR_RETRY. dag_id=mysql_insert_select, task_id=wait_for_model_file, execution_date=20250906T063210, start_date=20250906T063229, end_date=20250906T063436
[2025-09-06T06:34:36.033+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 387 for task wait_for_model_file (Task received SIGTERM signal; 131)
[2025-09-06T06:34:36.051+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=131, status='terminated', exitcode=1, started='06:32:28') (131) terminated with exit code 1
