[2025-09-06T01:50:20.322+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: mysql_insert_select.train_model manual__2025-09-06T01:50:06.816162+00:00 [queued]>
[2025-09-06T01:50:20.334+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: mysql_insert_select.train_model manual__2025-09-06T01:50:06.816162+00:00 [queued]>
[2025-09-06T01:50:20.335+0000] {taskinstance.py:1331} INFO - Starting attempt 1 of 1
[2025-09-06T01:50:20.353+0000] {taskinstance.py:1350} INFO - Executing <Task(PythonOperator): train_model> on 2025-09-06 01:50:06.816162+00:00
[2025-09-06T01:50:20.365+0000] {standard_task_runner.py:57} INFO - Started process 5528 to run task
[2025-09-06T01:50:20.377+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'mysql_insert_select', 'train_model', 'manual__2025-09-06T01:50:06.816162+00:00', '--job-id', '115', '--raw', '--subdir', 'DAGS_FOLDER/crea_tablas.py', '--cfg-path', '/tmp/tmpoz3i7zn8']
[2025-09-06T01:50:20.381+0000] {standard_task_runner.py:85} INFO - Job 115: Subtask train_model
[2025-09-06T01:50:20.469+0000] {task_command.py:410} INFO - Running <TaskInstance: mysql_insert_select.train_model manual__2025-09-06T01:50:06.816162+00:00 [running]> on host 72c5ffe25b48
[2025-09-06T01:50:20.651+0000] {taskinstance.py:1570} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='mysql_insert_select' AIRFLOW_CTX_TASK_ID='train_model' AIRFLOW_CTX_EXECUTION_DATE='2025-09-06T01:50:06.816162+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-09-06T01:50:06.816162+00:00'
[2025-09-06T01:50:20.671+0000] {base.py:73} INFO - Using connection ID 'mysql_conn' for task execution.
[2025-09-06T01:50:20.864+0000] {logging_mixin.py:149} INFO - Accuracy: 1.00
[2025-09-06T01:50:20.864+0000] {logging_mixin.py:149} INFO - Classification Report:
[2025-09-06T01:50:20.868+0000] {logging_mixin.py:149} INFO -               precision    recall  f1-score   support

           1       1.00      1.00      1.00        29
           2       1.00      1.00      1.00        14
           3       1.00      1.00      1.00        24

    accuracy                           1.00        67
   macro avg       1.00      1.00      1.00        67
weighted avg       1.00      1.00      1.00        67
[2025-09-06T01:50:20.868+0000] {taskinstance.py:1847} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/scripts/funciones.py", line 151, in train_model
    os.makedirs(model_dir, exist_ok=True)
  File "/usr/local/lib/python3.7/os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/usr/local/lib/python3.7/os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/usr/local/lib/python3.7/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/usr/local/airflow'
[2025-09-06T01:50:20.883+0000] {taskinstance.py:1373} INFO - Marking task as FAILED. dag_id=mysql_insert_select, task_id=train_model, execution_date=20250906T015006, start_date=20250906T015020, end_date=20250906T015020
[2025-09-06T01:50:20.905+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 115 for task train_model ([Errno 13] Permission denied: '/usr/local/airflow'; 5528)
[2025-09-06T01:50:20.943+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 1
[2025-09-06T01:50:20.988+0000] {taskinstance.py:2674} INFO - 0 downstream tasks scheduled from follow-on schedule check
