[2025-09-06T06:27:41.565+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: mysql_insert_select.train_model manual__2025-09-06T06:27:27.277447+00:00 [queued]>
[2025-09-06T06:27:41.580+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: mysql_insert_select.train_model manual__2025-09-06T06:27:27.277447+00:00 [queued]>
[2025-09-06T06:27:41.581+0000] {taskinstance.py:1331} INFO - Starting attempt 1 of 1
[2025-09-06T06:27:41.602+0000] {taskinstance.py:1350} INFO - Executing <Task(PythonOperator): train_model> on 2025-09-06 06:27:27.277447+00:00
[2025-09-06T06:27:41.615+0000] {standard_task_runner.py:57} INFO - Started process 1018 to run task
[2025-09-06T06:27:41.621+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'mysql_insert_select', 'train_model', 'manual__2025-09-06T06:27:27.277447+00:00', '--job-id', '376', '--raw', '--subdir', 'DAGS_FOLDER/mysql_insert_select.py', '--cfg-path', '/tmp/tmpr9fibebl']
[2025-09-06T06:27:41.625+0000] {standard_task_runner.py:85} INFO - Job 376: Subtask train_model
[2025-09-06T06:27:41.704+0000] {task_command.py:410} INFO - Running <TaskInstance: mysql_insert_select.train_model manual__2025-09-06T06:27:27.277447+00:00 [running]> on host 498c9c87b7f1
[2025-09-06T06:27:41.840+0000] {taskinstance.py:1570} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='mysql_insert_select' AIRFLOW_CTX_TASK_ID='train_model' AIRFLOW_CTX_EXECUTION_DATE='2025-09-06T06:27:27.277447+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-09-06T06:27:27.277447+00:00'
[2025-09-06T06:27:41.854+0000] {base.py:73} INFO - Using connection ID 'mysql_conn' for task execution.
[2025-09-06T06:27:41.915+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,

[2025-09-06T06:27:41.918+0000] {taskinstance.py:1847} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/scripts/funciones.py", line 145, in train_model
    joblib.dump(model, '/opt/airflow/models/RegresionLogistica.pkl')
  File "/home/airflow/.local/lib/python3.7/site-packages/joblib/numpy_pickle.py", line 552, in dump
    with open(filename, 'wb') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/models/RegresionLogistica.pkl'
[2025-09-06T06:27:41.942+0000] {taskinstance.py:1373} INFO - Marking task as FAILED. dag_id=mysql_insert_select, task_id=train_model, execution_date=20250906T062727, start_date=20250906T062741, end_date=20250906T062741
[2025-09-06T06:27:41.976+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 376 for task train_model ([Errno 2] No such file or directory: '/opt/airflow/models/RegresionLogistica.pkl'; 1018)
[2025-09-06T06:27:41.999+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 1
[2025-09-06T06:27:42.038+0000] {taskinstance.py:2674} INFO - 0 downstream tasks scheduled from follow-on schedule check
