[2025-09-06T01:46:29.536+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: mysql_insert_select.train_model manual__2025-09-06T01:46:15.107675+00:00 [queued]>
[2025-09-06T01:46:29.549+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: mysql_insert_select.train_model manual__2025-09-06T01:46:15.107675+00:00 [queued]>
[2025-09-06T01:46:29.550+0000] {taskinstance.py:1331} INFO - Starting attempt 1 of 1
[2025-09-06T01:46:29.574+0000] {taskinstance.py:1350} INFO - Executing <Task(PythonOperator): train_model> on 2025-09-06 01:46:15.107675+00:00
[2025-09-06T01:46:29.587+0000] {standard_task_runner.py:57} INFO - Started process 5423 to run task
[2025-09-06T01:46:29.596+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'mysql_insert_select', 'train_model', 'manual__2025-09-06T01:46:15.107675+00:00', '--job-id', '101', '--raw', '--subdir', 'DAGS_FOLDER/crea_tablas.py', '--cfg-path', '/tmp/tmpat80hxdd']
[2025-09-06T01:46:29.600+0000] {standard_task_runner.py:85} INFO - Job 101: Subtask train_model
[2025-09-06T01:46:29.678+0000] {task_command.py:410} INFO - Running <TaskInstance: mysql_insert_select.train_model manual__2025-09-06T01:46:15.107675+00:00 [running]> on host 72c5ffe25b48
[2025-09-06T01:46:29.825+0000] {taskinstance.py:1570} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='mysql_insert_select' AIRFLOW_CTX_TASK_ID='train_model' AIRFLOW_CTX_EXECUTION_DATE='2025-09-06T01:46:15.107675+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-09-06T01:46:15.107675+00:00'
[2025-09-06T01:46:29.848+0000] {base.py:73} INFO - Using connection ID 'mysql_conn' for task execution.
[2025-09-06T01:46:30.030+0000] {logging_mixin.py:149} INFO - Accuracy: 1.00
[2025-09-06T01:46:30.030+0000] {logging_mixin.py:149} INFO - Classification Report:
[2025-09-06T01:46:30.035+0000] {logging_mixin.py:149} INFO -               precision    recall  f1-score   support

           1       1.00      1.00      1.00        29
           2       1.00      1.00      1.00        14
           3       1.00      1.00      1.00        24

    accuracy                           1.00        67
   macro avg       1.00      1.00      1.00        67
weighted avg       1.00      1.00      1.00        67
[2025-09-06T01:46:30.035+0000] {taskinstance.py:1847} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/scripts/funciones.py", line 149, in train_model
    joblib.dump(model, '/usr/local/airflow/dags/models/RandomForestclassifier.pkl')
  File "/home/airflow/.local/lib/python3.7/site-packages/joblib/numpy_pickle.py", line 552, in dump
    with open(filename, 'wb') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/airflow/dags/models/RandomForestclassifier.pkl'
[2025-09-06T01:46:30.048+0000] {taskinstance.py:1373} INFO - Marking task as FAILED. dag_id=mysql_insert_select, task_id=train_model, execution_date=20250906T014615, start_date=20250906T014629, end_date=20250906T014630
[2025-09-06T01:46:30.068+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 101 for task train_model ([Errno 2] No such file or directory: '/usr/local/airflow/dags/models/RandomForestclassifier.pkl'; 5423)
[2025-09-06T01:46:30.087+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 1
[2025-09-06T01:46:30.111+0000] {taskinstance.py:2674} INFO - 0 downstream tasks scheduled from follow-on schedule check
