[2025-09-06T05:56:33.934+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: mysql_insert_select.test manual__2025-09-06T05:56:09.962676+00:00 [queued]>
[2025-09-06T05:56:33.953+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: mysql_insert_select.test manual__2025-09-06T05:56:09.962676+00:00 [queued]>
[2025-09-06T05:56:33.953+0000] {taskinstance.py:1331} INFO - Starting attempt 1 of 1
[2025-09-06T05:56:33.973+0000] {taskinstance.py:1350} INFO - Executing <Task(PythonOperator): test> on 2025-09-06 05:56:09.962676+00:00
[2025-09-06T05:56:33.986+0000] {standard_task_runner.py:57} INFO - Started process 350 to run task
[2025-09-06T05:56:33.992+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'mysql_insert_select', 'test', 'manual__2025-09-06T05:56:09.962676+00:00', '--job-id', '340', '--raw', '--subdir', 'DAGS_FOLDER/mysql_insert_select.py', '--cfg-path', '/tmp/tmphyssy8k2']
[2025-09-06T05:56:34.000+0000] {standard_task_runner.py:85} INFO - Job 340: Subtask test
[2025-09-06T05:56:34.083+0000] {task_command.py:410} INFO - Running <TaskInstance: mysql_insert_select.test manual__2025-09-06T05:56:09.962676+00:00 [running]> on host 498c9c87b7f1
[2025-09-06T05:56:34.223+0000] {taskinstance.py:1570} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='mysql_insert_select' AIRFLOW_CTX_TASK_ID='test' AIRFLOW_CTX_EXECUTION_DATE='2025-09-06T05:56:09.962676+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-09-06T05:56:09.962676+00:00'
[2025-09-06T05:56:34.227+0000] {logging_mixin.py:149} INFO - <class 'sklearn.linear_model._logistic.LogisticRegression'>
[2025-09-06T05:56:34.228+0000] {logging_mixin.py:149} INFO - Modelo cargado correctamente: <class 'sklearn.linear_model._logistic.LogisticRegression'>
[2025-09-06T05:56:34.229+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  "X does not have valid feature names, but"

[2025-09-06T05:56:34.230+0000] {logging_mixin.py:149} INFO - Predicci√≥n de prueba: [1]
[2025-09-06T05:56:34.230+0000] {python.py:183} INFO - Done. Returned value was: None
[2025-09-06T05:56:34.252+0000] {taskinstance.py:1373} INFO - Marking task as SUCCESS. dag_id=mysql_insert_select, task_id=test, execution_date=20250906T055609, start_date=20250906T055633, end_date=20250906T055634
[2025-09-06T05:56:34.286+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 0
[2025-09-06T05:56:34.312+0000] {taskinstance.py:2674} INFO - 0 downstream tasks scheduled from follow-on schedule check
