[2025-09-06T01:48:56.686+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: mysql_insert_select.train_model manual__2025-09-06T01:48:42.332485+00:00 [queued]>
[2025-09-06T01:48:56.699+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: mysql_insert_select.train_model manual__2025-09-06T01:48:42.332485+00:00 [queued]>
[2025-09-06T01:48:56.700+0000] {taskinstance.py:1331} INFO - Starting attempt 1 of 1
[2025-09-06T01:48:56.719+0000] {taskinstance.py:1350} INFO - Executing <Task(PythonOperator): train_model> on 2025-09-06 01:48:42.332485+00:00
[2025-09-06T01:48:56.735+0000] {standard_task_runner.py:57} INFO - Started process 5489 to run task
[2025-09-06T01:48:56.746+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'mysql_insert_select', 'train_model', 'manual__2025-09-06T01:48:42.332485+00:00', '--job-id', '108', '--raw', '--subdir', 'DAGS_FOLDER/crea_tablas.py', '--cfg-path', '/tmp/tmpurs68js8']
[2025-09-06T01:48:56.751+0000] {standard_task_runner.py:85} INFO - Job 108: Subtask train_model
[2025-09-06T01:48:56.832+0000] {task_command.py:410} INFO - Running <TaskInstance: mysql_insert_select.train_model manual__2025-09-06T01:48:42.332485+00:00 [running]> on host 72c5ffe25b48
[2025-09-06T01:48:56.991+0000] {taskinstance.py:1570} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='mysql_insert_select' AIRFLOW_CTX_TASK_ID='train_model' AIRFLOW_CTX_EXECUTION_DATE='2025-09-06T01:48:42.332485+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-09-06T01:48:42.332485+00:00'
[2025-09-06T01:48:57.007+0000] {base.py:73} INFO - Using connection ID 'mysql_conn' for task execution.
[2025-09-06T01:48:57.179+0000] {logging_mixin.py:149} INFO - Accuracy: 1.00
[2025-09-06T01:48:57.179+0000] {logging_mixin.py:149} INFO - Classification Report:
[2025-09-06T01:48:57.184+0000] {logging_mixin.py:149} INFO -               precision    recall  f1-score   support

           1       1.00      1.00      1.00        29
           2       1.00      1.00      1.00        14
           3       1.00      1.00      1.00        24

    accuracy                           1.00        67
   macro avg       1.00      1.00      1.00        67
weighted avg       1.00      1.00      1.00        67
[2025-09-06T01:48:57.184+0000] {taskinstance.py:1847} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/scripts/funciones.py", line 149, in train_model
    j# Crear directorio si no existe
NameError: name 'j' is not defined
[2025-09-06T01:48:57.197+0000] {taskinstance.py:1373} INFO - Marking task as FAILED. dag_id=mysql_insert_select, task_id=train_model, execution_date=20250906T014842, start_date=20250906T014856, end_date=20250906T014857
[2025-09-06T01:48:57.214+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 108 for task train_model (name 'j' is not defined; 5489)
[2025-09-06T01:48:57.232+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 1
[2025-09-06T01:48:57.265+0000] {taskinstance.py:2674} INFO - 0 downstream tasks scheduled from follow-on schedule check
