[2025-09-06T06:20:36.318+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: mysql_insert_select.insert_penguins manual__2025-09-06T06:20:33.411735+00:00 [queued]>
[2025-09-06T06:20:36.345+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: mysql_insert_select.insert_penguins manual__2025-09-06T06:20:33.411735+00:00 [queued]>
[2025-09-06T06:20:36.345+0000] {taskinstance.py:1331} INFO - Starting attempt 1 of 1
[2025-09-06T06:20:36.401+0000] {taskinstance.py:1350} INFO - Executing <Task(PythonOperator): insert_penguins> on 2025-09-06 06:20:33.411735+00:00
[2025-09-06T06:20:36.428+0000] {standard_task_runner.py:57} INFO - Started process 796 to run task
[2025-09-06T06:20:36.442+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'mysql_insert_select', 'insert_penguins', 'manual__2025-09-06T06:20:33.411735+00:00', '--job-id', '350', '--raw', '--subdir', 'DAGS_FOLDER/mysql_insert_select.py', '--cfg-path', '/tmp/tmpcaji37k0']
[2025-09-06T06:20:36.448+0000] {standard_task_runner.py:85} INFO - Job 350: Subtask insert_penguins
[2025-09-06T06:20:36.550+0000] {task_command.py:410} INFO - Running <TaskInstance: mysql_insert_select.insert_penguins manual__2025-09-06T06:20:33.411735+00:00 [running]> on host 498c9c87b7f1
[2025-09-06T06:20:36.686+0000] {taskinstance.py:1570} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='mysql_insert_select' AIRFLOW_CTX_TASK_ID='insert_penguins' AIRFLOW_CTX_EXECUTION_DATE='2025-09-06T06:20:33.411735+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-09-06T06:20:33.411735+00:00'
[2025-09-06T06:20:36.726+0000] {base.py:73} INFO - Using connection ID 'mysql_conn' for task execution.
[2025-09-06T06:20:36.750+0000] {taskinstance.py:1847} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/scripts/funciones.py", line 48, in insert_data
    cursor.execute(sql, values)
  File "/home/airflow/.local/lib/python3.7/site-packages/MySQLdb/cursors.py", line 206, in execute
    res = self._query(query)
  File "/home/airflow/.local/lib/python3.7/site-packages/MySQLdb/cursors.py", line 319, in _query
    db.query(q)
  File "/home/airflow/.local/lib/python3.7/site-packages/MySQLdb/connections.py", line 254, in query
    _mysql.connection.query(self, query)
MySQLdb.ProgrammingError: (1146, "Table 'my_app_db.penguins_raw' doesn't exist")
[2025-09-06T06:20:36.763+0000] {taskinstance.py:1373} INFO - Marking task as FAILED. dag_id=mysql_insert_select, task_id=insert_penguins, execution_date=20250906T062033, start_date=20250906T062036, end_date=20250906T062036
[2025-09-06T06:20:36.789+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 350 for task insert_penguins ((1146, "Table 'my_app_db.penguins_raw' doesn't exist"); 796)
[2025-09-06T06:20:36.818+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 1
[2025-09-06T06:20:36.896+0000] {taskinstance.py:2674} INFO - 0 downstream tasks scheduled from follow-on schedule check
