[2025-09-06T01:03:09.619+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: mysql_insert_select.read_data manual__2025-09-06T01:02:58.255309+00:00 [queued]>
[2025-09-06T01:03:09.635+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: mysql_insert_select.read_data manual__2025-09-06T01:02:58.255309+00:00 [queued]>
[2025-09-06T01:03:09.636+0000] {taskinstance.py:1331} INFO - Starting attempt 1 of 1
[2025-09-06T01:03:09.661+0000] {taskinstance.py:1350} INFO - Executing <Task(PythonOperator): read_data> on 2025-09-06 01:02:58.255309+00:00
[2025-09-06T01:03:09.673+0000] {standard_task_runner.py:57} INFO - Started process 4579 to run task
[2025-09-06T01:03:09.682+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'mysql_insert_select', 'read_data', 'manual__2025-09-06T01:02:58.255309+00:00', '--job-id', '63', '--raw', '--subdir', 'DAGS_FOLDER/crea_tablas.py', '--cfg-path', '/tmp/tmp_vh0suy4']
[2025-09-06T01:03:09.688+0000] {standard_task_runner.py:85} INFO - Job 63: Subtask read_data
[2025-09-06T01:03:09.782+0000] {task_command.py:410} INFO - Running <TaskInstance: mysql_insert_select.read_data manual__2025-09-06T01:02:58.255309+00:00 [running]> on host 72c5ffe25b48
[2025-09-06T01:03:09.938+0000] {taskinstance.py:1570} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='mysql_insert_select' AIRFLOW_CTX_TASK_ID='read_data' AIRFLOW_CTX_EXECUTION_DATE='2025-09-06T01:02:58.255309+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-09-06T01:02:58.255309+00:00'
[2025-09-06T01:03:09.955+0000] {base.py:73} INFO - Using connection ID 'mysql_conn' for task execution.
[2025-09-06T01:03:10.006+0000] {taskinstance.py:1847} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/indexes/base.py", line 3361, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas/_libs/index.pyx", line 76, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 108, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 5198, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 5206, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'island_Biscoe'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/scripts/funciones.py", line 131, in read_data
    for _, row in cleaned_df.iterrows()
  File "/opt/airflow/dags/scripts/funciones.py", line 131, in <listcomp>
    for _, row in cleaned_df.iterrows()
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/series.py", line 942, in __getitem__
    return self._get_value(key)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/series.py", line 1051, in _get_value
    loc = self.index.get_loc(label)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/indexes/base.py", line 3363, in get_loc
    raise KeyError(key) from err
KeyError: 'island_Biscoe'
[2025-09-06T01:03:10.026+0000] {taskinstance.py:1373} INFO - Marking task as FAILED. dag_id=mysql_insert_select, task_id=read_data, execution_date=20250906T010258, start_date=20250906T010309, end_date=20250906T010310
[2025-09-06T01:03:10.055+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 63 for task read_data ('island_Biscoe'; 4579)
[2025-09-06T01:03:10.090+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 1
[2025-09-06T01:03:10.130+0000] {taskinstance.py:2674} INFO - 0 downstream tasks scheduled from follow-on schedule check
