[2025-09-06T06:59:25.435+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: orquestador.create_table_raw scheduled__2023-01-01T00:00:00+00:00 [queued]>
[2025-09-06T06:59:25.450+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: orquestador.create_table_raw scheduled__2023-01-01T00:00:00+00:00 [queued]>
[2025-09-06T06:59:25.451+0000] {taskinstance.py:1331} INFO - Starting attempt 1 of 1
[2025-09-06T06:59:25.481+0000] {taskinstance.py:1350} INFO - Executing <Task(MySqlOperator): create_table_raw> on 2023-01-01 00:00:00+00:00
[2025-09-06T06:59:25.493+0000] {standard_task_runner.py:57} INFO - Started process 140 to run task
[2025-09-06T06:59:25.498+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'orquestador', 'create_table_raw', 'scheduled__2023-01-01T00:00:00+00:00', '--job-id', '442', '--raw', '--subdir', 'DAGS_FOLDER/orquestador.py', '--cfg-path', '/tmp/tmppuaa9kdy']
[2025-09-06T06:59:25.504+0000] {standard_task_runner.py:85} INFO - Job 442: Subtask create_table_raw
[2025-09-06T06:59:25.596+0000] {task_command.py:410} INFO - Running <TaskInstance: orquestador.create_table_raw scheduled__2023-01-01T00:00:00+00:00 [running]> on host 32a81c69218b
[2025-09-06T06:59:25.727+0000] {taskinstance.py:1570} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='orquestador' AIRFLOW_CTX_TASK_ID='create_table_raw' AIRFLOW_CTX_EXECUTION_DATE='2023-01-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-01-01T00:00:00+00:00'
[2025-09-06T06:59:25.727+0000] {sql.py:262} INFO - Executing:  CREATE TABLE penguins_raw (
            species VARCHAR(50) NULL,
            island VARCHAR(50) NULL,
            bill_length_mm DOUBLE NULL,
            bill_depth_mm DOUBLE NULL,
            flipper_length_mm DOUBLE NULL,
            body_mass_g DOUBLE NULL,
            sex VARCHAR(10) NULL,
            year INT NULL
        )
        
[2025-09-06T06:59:25.741+0000] {base.py:73} INFO - Using connection ID 'mysql_conn' for task execution.
[2025-09-06T06:59:25.823+0000] {base.py:73} INFO - Using connection ID 'mysql_conn' for task execution.
[2025-09-06T06:59:25.839+0000] {sql.py:375} INFO - Running statement:  CREATE TABLE penguins_raw (
            species VARCHAR(50) NULL,
            island VARCHAR(50) NULL,
            bill_length_mm DOUBLE NULL,
            bill_depth_mm DOUBLE NULL,
            flipper_length_mm DOUBLE NULL,
            body_mass_g DOUBLE NULL,
            sex VARCHAR(10) NULL,
            year INT NULL
        )
        , parameters: None
[2025-09-06T06:59:25.846+0000] {taskinstance.py:1847} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/operators/sql.py", line 274, in execute
    **extra_kwargs,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/hooks/sql.py", line 349, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/hooks/sql.py", line 380, in _run_command
    cur.execute(sql_statement)
  File "/home/airflow/.local/lib/python3.7/site-packages/MySQLdb/cursors.py", line 206, in execute
    res = self._query(query)
  File "/home/airflow/.local/lib/python3.7/site-packages/MySQLdb/cursors.py", line 319, in _query
    db.query(q)
  File "/home/airflow/.local/lib/python3.7/site-packages/MySQLdb/connections.py", line 254, in query
    _mysql.connection.query(self, query)
MySQLdb.OperationalError: (1050, "Table 'penguins_raw' already exists")
[2025-09-06T06:59:25.860+0000] {taskinstance.py:1373} INFO - Marking task as FAILED. dag_id=orquestador, task_id=create_table_raw, execution_date=20230101T000000, start_date=20250906T065925, end_date=20250906T065925
[2025-09-06T06:59:25.877+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 442 for task create_table_raw ((1050, "Table 'penguins_raw' already exists"); 140)
[2025-09-06T06:59:25.916+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 1
[2025-09-06T06:59:25.956+0000] {taskinstance.py:2674} INFO - 0 downstream tasks scheduled from follow-on schedule check
